#ifndef VAULT_UI_TEXT_H
#define VAULT_UI_TEXT_H

typedef enum {
    TXT_WINDOW,TXT_TITLE,TXT_LANGUAGE,TXT_INTRO,TXT_LOCATION,TXT_KEY,TXT_HOSTS,
    TXT_PASSWORD,TXT_CONFIRM,TXT_ADD,TXT_REMOVE,TXT_BROWSE,TXT_BACKUP,TXT_OPEN,TXT_FOOTER,
    TXT_DATE,TXT_STATUS,TXT_SIZE,TXT_PATH,TXT_HASH,TXT_DETAIL,
    TXT_READY,TXT_CONNECTING,TXT_THREAD_ERROR,TXT_EXPORT,TXT_ENCRYPT,TXT_VERIFY,TXT_SAVE,
    TXT_SUCCESS,TXT_FAILURE,TXT_ALL_FILES,TXT_CHOOSE_FOLDER,TXT_LOCATION_ERROR,
    TXT_PASSWORD_ERROR,TXT_PASSWORD_TITLE,TXT_RECORD,TXT_RECORD_FORMAT,
    TXT_HISTORY_ERROR,TXT_CLOSE_ERROR,TXT_BUSY,TXT_FOLDER_MISSING,TXT_FOLDER_OPEN_ERROR,
    TXT_RECOVER,TXT_SOURCE,TXT_RECOVER_NOTE,TXT_RECOVER_READY,TXT_RECOVER_RUNNING,TXT_RECOVER_SUCCESS,
    TXT_RECOVER_PASSWORD,TXT_RECOVER_PATH,TXT_RECOVER_DIRECTORY,TXT_RECOVER_AUTH,TXT_RECOVER_FORMAT,TXT_RECOVER_SAVE,
    TXT_COPY,TXT_COPIED,TXT_COPY_ERROR,TXT_OK,TXT_RECORD_PATH,
    TXT_VBK_FILES,TXT_MODE_BACKUP,TXT_MODE_RECOVER,TXT_RECOVER_OPEN,TXT_RECOVER_DONE,TXT_RECOVER_CLEANUP,TXT_RECOVER_LOCATION,TXT_SIZE_BYTES,
    TXT_DELETE_RECORD,TXT_DELETE_CONFIRM,TXT_DELETE_ERROR,TXT_DELETE_DONE,
    TXT_DELETE_DATA_CHECK,TXT_DELETE_FINAL_RECORD,TXT_DELETE_FINAL_DATA,TXT_DELETE_DATA_ERROR,
    TXT_DELETE_DATA_DONE,TXT_DELETE_PARTIAL_ERROR,TXT_RECOVER_VM,TXT_RECOVER_VM_CONFIRM,TXT_RECOVER_VM_SUCCESS,TXT_RECOVER_VM_DONE,TXT_RECOVER_VM_ERROR,TXT_RECOVER_VM_TRANSFER,TXT_RECOVER_VM_VALIDATE,TXT_RECOVER_VM_APPLY,TXT_RECOVER_VM_CHECK,TXT_COUNT
} UiText;

static const wchar_t *const ui_text[TXT_COUNT]={
    L"Bitwarden Vault Backup & Recover",
    L"Bitwarden Vault Backup & Recover",
    L"Language",
    L"Local encrypted backups and recovery. Passwords are never saved.",
    L"Destination",L"SSH key",L"Known hosts",
    L"Password",L"Confirm",
    L"Add folder",L"Remove",L"Browse",
    L"Back up now",L"Open backup folder",
    L"Double-click a record for details.",
    L"Time (UTC)",L"Status",L"Size",
    L"Backup path",L"SHA256",L"Details",
    L"Ready. Passwords are never saved; history is retained. Local paths: up to 220 characters.",
    L"Connecting to the VM. Services pause briefly for the snapshot. Keep Windows and the VM running.",
    L"Unable to start the background worker.",
    L"Exporting: services resume after the snapshot, before compression and transfer.",
    L"Encrypting with AES-256-GCM. The password is used only for this backup.",
    L"Decrypting the saved data to verify its integrity.",
    L"Saving to the destination disk; the verified file is renamed atomically.",
    L"Backup saved and verified. Keep the password safe; upload the encrypted .tar.zst.vbk file manually.",
    L"Backup failed. Double-click its history record for details.",
    L"All files\0*.*\0\0",
    L"Choose a local backup folder (full path: up to 220 characters)",
    L"Use a local drive path with no more than 220 characters.",
    L"Use at least 12 characters and enter the same password twice. Store it outside this vault.",
    L"Backup password",L"Backup record",
    L"Path: %ls\n\nSHA256: %ls\n\nDetails: %ls",
    L"Backup saved; history could not be updated",
    L"A task is running. Wait for it to finish before closing.",
    L"Task in progress",
    L"The backup folder does not exist or cannot be accessed. Check the destination and drive connection; the first successful backup creates the folder.",
    L"Unable to open the backup folder. Check folder permissions and Windows File Explorer.",
    L"Recover",L"Backup file",
    L"Creates .tar.zst. Follow the README to extract files and rebuild the service.",
    L"Select a backup and enter its password. VM mode uses private staging; the selected folder is for decrypt-only mode.",
    L"Authenticating; VM mode transfers, validates, restores data and checks private HTTPS.",
    L"Recovery completed. Output contains sensitive plaintext; follow the README to extract files and rebuild the service.\n\n%ls",
    L"Select an encrypted backup and enter its original password once.",
    L"Choose an existing local drive folder; the complete output path must be shorter than 260 characters.",
    L"Unable to create a protected recovery folder. Choose a disk supporting Windows permissions and check write access.",
    L"Recovery failed: incorrect password, damaged backup or disk write failure. No completed recovery file was saved.",
    L"Authentication passed, but the content is not a supported zstd backup.",
    L"Unable to finish saving the recovered file. Check the disk and permissions.",
    L"Copy",L"Copied",
    L"Unable to copy the path. Please try again.",
    L"OK",L"Path",
    L"Encrypted backups (*.vbk)\0*.vbk\0All files\0*.*\0\0",
    L"Backup",L"Recovery",L"Open recovery result",
    L"Recovery completed. Open the recovery folder; follow the README to extract files and rebuild the service.",
    L"Local cleanup was incomplete. Sensitive plaintext may remain; inspect and clean this folder:\n\n%ls",
    L"Decrypt folder",
    L"%llu bytes",
    L"Delete record",
    L"Delete this backup history record? The file is kept by default; select the option below to also delete this backup file.\n\nTime: %ls\nPath: %ls",
    L"Unable to delete the history record. Check state folder permissions and disk space.",
    L"History record deleted. The backup file remains on disk.",
    L"Also delete the backup file from disk (permanently)",
    L"Final confirmation: delete only the history record and keep the file. Continue?\n\nTime: %ls\nPath: %ls",
    L"Final confirmation: delete the history record and permanently delete the backup file below without using the Recycle Bin. Other records referencing this file will also lose access to it. Continue?\n\nTime: %ls\nPath: %ls",
    L"Unable to delete the backup file (Windows error %lu). The history record was kept. Check the path, permissions or whether the file is in use.\n\n%ls",
    L"History record deleted; the backup file was deleted or was already absent.",
    L"The backup file was deleted or already absent, but deleting its history record failed. The record was kept; retry deleting the record.",
    L"Restore the Bitwarden vault on the VM (uncheck to decrypt only)",
    L"Replace the Bitwarden vault on VM %ls with this backup? Service will stop temporarily; newer data will no longer appear. The previous deployment/container is retained and failures attempt rollback. The VM must be running and reachable by SSH.\n\nBackup: %ls",
    L"Bitwarden data restored on the VM; container started and private HTTPS/API checks passed. Local plaintext cleaned. Previous deployment retained at /opt/bitwarden-before-recover-*. Sign in to check items, synchronization and attachments.",
    L"VM restored; private HTTPS/API checks passed.",
    L"VM recovery was not confirmed. Check connectivity, SSH settings and /var/backups/bitwarden/recover-*/status.json on the VM; a disconnected client does not mean the remote operation stopped.",
    L"Transferring the authenticated backup over SSH.",
    L"Validating compression, archive, database and image on the VM.",
    L"Retaining the previous deployment and restoring database, configuration and keys.",
    L"Starting Bitwarden and checking private HTTPS/API."
};
/* Translate legacy diagnostics for display while retaining stored records. */
static const wchar_t *const diagnostic_text[][2]={
    {L"\u65e7\u5bb9\u5668\u6e05\u7406\u672a\u5b8c\u6210。\u8bf7\u68c0\u67e5 VM \u6062\u590d journal，\u5904\u7406\u6b8b\u7559\u65e7\u5bb9\u5668\u540e\u518d\u6267\u884c Compose \u7ef4\u62a4。",L"Previous-container cleanup was incomplete. Check the recovery journal and handle the retained old container before Compose maintenance."},
    {L"SSH \u6062\u590d\u8c03\u7528\u5931\u8d25。\u8bf7\u68c0\u67e5 Tailscale、SSH \u5bc6\u94a5、known_hosts \u548c VM \u6062\u590d\u52a9\u624b。",L"SSH recovery failed. Check Tailscale, the SSH key, known_hosts and the VM recovery helper."},
    {L"\u8fdc\u7aef\u672a\u8fd4\u56de\u5b8c\u6574\u6062\u590d\u6210\u529f\u51ed\u636e。\u8bf7\u68c0\u67e5 VM \u6062\u590d\u72b6\u6001。",L"The remote helper did not return a recovery success receipt. Check recovery status on the VM."},
    {L"\u65e0\u6cd5\u751f\u6210\u5b89\u5168\u968f\u673a\u6570。",L"Unable to generate secure random data."},
    {L"\u8bf7\u9009\u62e9\u672c\u673a\u78c1\u76d8\u4e0a\u7684\u76ee\u5f55，\u8def\u5f84\u957f\u5ea6\u4e0d\u8d85\u8fc7 220 \u5b57\u7b26。",L"Choose a local drive folder with a path of at most 220 characters."},
    {L"\u65e0\u6cd5\u521b\u5efa\u5907\u4efd\u76ee\u5f55，\u6216\u6240\u9009\u4f4d\u7f6e\u4e0d\u662f\u76ee\u5f55。",L"Unable to create the backup folder, or the destination is not a folder."},
    {L"\u65e0\u6cd5\u521b\u5efa\u4ec5\u5f53\u524d\u7528\u6237\u548c SYSTEM \u53ef\u8bbf\u95ee\u7684\u6682\u5b58\u76ee\u5f55。",L"Unable to create a staging folder restricted to the current user and SYSTEM."},
    {L"\u5bfc\u51fa\u6587\u4ef6\u4e0d\u662f\u6709\u6548\u7684 zstd \u6570\u636e\u6d41。",L"The exported file is not a valid zstd stream."},
    {L"\u52a0\u5bc6\u5931\u8d25，\u8bf7\u68c0\u67e5\u78c1\u76d8\u7a7a\u95f4\u548c\u5199\u5165\u6743\u9650。",L"Encryption failed. Check disk space and write permissions."},
    {L"\u52a0\u5bc6\u540e\u7684\u56de\u8bfb\u9a8c\u8bc1\u5931\u8d25，\u672a\u4fdd\u5b58\u4e3a\u6210\u529f\u5907\u4efd。",L"Verification after encryption failed; no successful backup was saved."},
    {L"\u65e0\u6cd5\u8ba1\u7b97\u5907\u4efd\u6821\u9a8c\u503c。",L"Unable to calculate the backup checksum."},
    {L"\u65e0\u6cd5\u4fdd\u5b58\u5230\u5907\u4efd\u76ee\u5f55，\u8bf7\u68c0\u67e5\u7a7a\u95f4\u548c\u6743\u9650。",L"Unable to save to the backup folder. Check space and permissions."},
    {L"\u76ee\u6807\u78c1\u76d8\u6821\u9a8c\u5931\u8d25。",L"Destination disk verification failed."},
    {L"\u65e0\u6cd5\u5237\u65b0\u76ee\u6807\u6587\u4ef6。",L"Unable to flush the destination file."},
    {L"\u65e0\u6cd5\u5b8c\u6210\u5907\u4efd\u6587\u4ef6\u7684\u539f\u5b50\u4fdd\u5b58，\u6216\u6587\u4ef6\u540d\u5df2\u5b58\u5728。",L"Unable to save the backup atomically, or the file already exists."},
    {L"\u5386\u53f2\u8bb0\u5f55\u5199\u5165\u5931\u8d25；\u8bf7\u68c0\u67e5\u72b6\u6001\u76ee\u5f55\u6743\u9650\u548c\u7a7a\u95f4。",L"Unable to write history. Check the state folder's permissions and free space."},
    {L"SSH \u5bfc\u51fa\u5931\u8d25（Windows \u9519\u8bef ",L"SSH export failed (Windows error "},
    {L"）。\u8bf7\u68c0\u67e5 Tailscale、SSH \u5bc6\u94a5\u548c VM \u5907\u4efd\u52a9\u624b。",L"). Check Tailscale, the SSH key and the VM backup helper."}
};
#endif
